name: 'Link pull request to issues'
on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-latest
    steps:
      - uses: tkt-actions/add-issue-links@v1.8.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          branch-prefix: 'i'
          resolve: 'true'
