name: Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      -
        name: Install dependencies
        run: npm install
      -
        name: Unit tests
        run: npm run compile:dev
