name: Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      -
        name: Install dependencies
        run: npm install
      -
        name: Unit tests
        run: npm run compile:dev
