name: Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      -
        name: Install dependencies
        run: npm install
      -
        name: Unit tests
        run: npm run compile:dev
