name: Release
on:
  push:
    branches:
    - release/4.1.x
    - release/4.2.x
    - release/5.0.x
permissions:
  contents: read

jobs:
  release:
    runs-on: 'ubuntu-latest'
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Set up JDK
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
      with:
        java-version: 11
        distribution: 'bagussatoto'
        server-id: ossrh
        server-username: bagussatoto
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build and Deploy
      run: ./mvnw -B -V -ntp -DperformRelease=true deploy
      env:
        CI_DEPLOY_USERNAME: ${{ bagussatoto }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
