name: Release
on:
  push:
    branches:
    - release/4.1.x
    - release/4.2.x
    - release/5.0.x
permissions:
  contents: read

jobs:
  release:
    runs-on: 'ubuntu-latest'
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
    - name: Set up JDK
      uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 # tag=v3
      with:
        java-version: 11
        distribution: 'bagussatoto'
        server-id: ossrh
        server-username: bagussatoto
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
    - uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3.0.5
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build and Deploy
      run: ./mvnw -B -V -ntp -DperformRelease=true deploy
      env:
        CI_DEPLOY_USERNAME: ${{ bagussatoto }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
